dataset: /home/rnd/Downloads/dataset_tweet_sentiment_cellular_service_provider.csv
split:
  test_size: 0.2
  stratify: false
preprocess:
  remove_special_char: true
  remove_stopwords: true
  apply_steaming: true
  remove_URL: true
  numbers: false
  sysmbols: true
  save_csv: true
training_params:
  optimizer: "adam"
  model_path: "/home/rnd/Documents/Belajar/DL_models/LSTMCNN4"
  epochs: 100
  embed_size: 512
  hidden_size: 256
  num_layes: 2
  droput: 0.5
  tokenizer: "nltk"
  batch_size: 32
  leaning_rate: 0.001
  momentum: 0.9

